# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_github_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='owned_issues_count',
            field=models.IntegerField(default=0),
        ),
    ]
