# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 16:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_owned_issues_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='owner',
        ),
        migrations.AddField(
            model_name='issue',
            name='assignee_login',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='creator_login',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repo',
            name='stargazers',
            field=models.ManyToManyField(related_name='starred_repos', to=settings.AUTH_USER_MODEL),
        ),
    ]
