# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160405_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='repo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='api.Repo'),
        ),
    ]
