# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-01 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160411_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_synced',
            field=models.DateTimeField(null=True),
        ),
    ]
