# Generated by Django 3.0 on 2019-12-12 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_last_synced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='repo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='api.Repo'),
        ),
    ]
